version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development

  redis:
    image: "redis:alpine"
    ports:
      - "6378:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile 
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0 
    volumes:
      - .:/app

volumes:
  postgres_data: