"""update order config

Revision ID: 21955bf7fdfd
Revises: f5b7cae1ddc8
Create Date: 2024-10-28 10:59:20.154659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21955bf7fdfd'
down_revision: Union[str, None] = 'f5b7cae1ddc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
